# Generated by Django 5.0.2 on 2024-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("litereview", "0002_userblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tickets"),
        ),
    ]
